name: COMPANIONSTICK
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0  # Use a known compatible version
  provider: ^6.1.2
  latlong2: ^0.9.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0
  geolocator: ^12.0.0  # Use a known compatible version
  haptic_feedback: ^0.5.1+1
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_database: ^11.1.4
  open_route_service: ^1.2.7
  animated_text_kit: ^4.2.2
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.5
  flutter_typeahead: ^5.2.0
  vector_math: ^2.1.4


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/walking_stick.png"

flutter:
  uses-material-design: true
  assets:
    - assets/walking_stick.png
    - assets/button_click.wav
    - assets/marker.png
    - assets/google_logo.png
